export enum ErrorCode {
  CORE_INVALID_ARG = 'CORE_001',
  CORE_NOT_FOUND = 'CORE_002',
  CORE_WEBGL_FAILURE = 'CORE_003',
  CORE_STATE_ERROR = 'CORE_004',
  RES_DISPOSED = 'RES_001',
  RES_INVALID_ARG = 'RES_002',
  RES_GL_ERROR = 'RES_003',
  MATH_INVALID_ARG = 'MATH_001',
  MATH_OUT_OF_BOUNDS = 'MATH_002',
  MATH_DIVIDE_BY_ZERO = 'MATH_003',
  MATH_NON_INVERTIBLE = 'MATH_004',
}
